[package]
name = "error_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for library...
thiserror = "1.0"
# for binary
anyhow = "1.0"